poppy:
  poppy_upper_body_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - abs_y
      - abs_x
      - abs_z
      - bust_y
      - bust_x
      - head_z
      - head_y
      - l_shoulder_y
      - l_shoulder_x
      - l_arm_z
      - l_elbow_y
      - r_shoulder_y
      - r_shoulder_x
      - r_arm_z
      - r_elbow_y
  poppy_lower_body_controller:
    # type: effort_controllers/JointEffortController
    type: effort_controllers/JointGroupEffortController
    # type: position_controllers/JointTrajectoryController
    # type: velocity_controllers/JointTrajectoryController
    # type: effort_controllers/JointTrajectoryController
    joints:
      - r_hip_x
      - r_hip_z
      - r_hip_y
      - r_knee_y
      - r_ankle_y
      - l_hip_x
      - l_hip_z
      - l_hip_y
      - l_knee_y
      - l_ankle_y
