tiger:
  #publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort Controllers
  wheel1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_FR_wheel_link_joint1
    pid: {p: 100.0, i: 0.1, d: 10.0}
  wheel2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_FR_wheel_link_joint2
    pid: {p: 100.0, i: 0.1, d: 10.0}
  wheel3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_FR_wheel_link_joint3
    pid: {p: 100.0, i: 0.1, d: 10.0}
  wheel4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_FR_wheel_link_joint4
    pid: {p: 100.0, i: 0.1, d: 10.0}
