tiger:
    tiger_ur10_controller:
      ur10_custom_shoulder_pan_joint/pid: {p: 0.0, i: 0.0, d: 0.0}
      ur10_custom_shoulder_lift_joint/pid: {p: 0.0, i: 0.0, d: 0.0}
      ur10_custom_elbow_joint/pid: {p: 0.0, i: 0, d: 0.0}
      ur10_custom_wrist_1_joint/pid: {p: 0.0, i: 0, d: 0.0}
      ur10_custom_wrist_2_joint/pid: {p: 0.0, i: 0, d: 0.0}
      ur10_custom_wrist_3_joint/pid: {p: 0.0, i: 0, d: 0.0}
